import { Poppins } from "next/font/google";
import "./globals.css";
import QueryClientProviderWrapper from "@/provider/query-client-provider";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryClientProviderWrapper>
          {children}
          <Toaster position="top-center" richColors />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
